var rv = require('russell-view')
var wayfarer = require('wayfarer')
var login = require('./modulos/login/login.js')
var menu = require('./modulos/menu_hidden/menu_hidden.js')
var cuadro = require('./modulos/cuadro/cuadro.js')
var timeline = require('./seccion/timeline.js')
// var timelineget = require('./seccion/timeline.get.js')
var azimuth = require('./seccion/azimuth.js')
var noticias = require('./seccion/noticias.js')
var noticiasget = require('./seccion/noticias.get.js')
// var eventos = require('./seccion/eventos.js')
// var eventosget = require('./seccion/eventos.get.js')
var router = wayfarer('/404')
module.exports = function app(state) {
  console.log(state.windowWidth)
  // router.on('/', function () {return menu(state)})
  // router.on('/', function (){return login(state)})
  router.on('/', function() {noticiasget(); return noticias(state)})
  router.on('/azimuth', function () {return azimuth(state)})
  router.on('/historia', /*function () {return timelineget(state)}, */function () {return timeline(state)})
  // router.on('/events', function () {return eventosget(state)}[>, function () {return eventos(state)}<])
  router.on('/brujula', function () {return brujula(state)})
  router.on('/404', function () {return undefined})
  return router(state.url)
}
